config_settings = {
    "sast": {
        "type": "command",
        "help": "Extract inventory data from a SAST instance",
        "description": "Extract inventory data from a SAST instance",
        "small": None,
        "required": False,
        "isdefault": True,
        "default": None,
        "aliases": ["cxsast"] },
    "cxone": {
        "type": "command",
        "help": "Extract inventory data from a CxONE tenant",
        "description": "Extract inventory data from a CxONE tenant",
        "small": None,
        "required": False,
        "isdefault": False,
        "default": None },
    "sca": {
        "type": "command",
        "help": "Extract inventory data from a SCA tenant",
        "description": "Extract inventory data from a SCA tenant",
        "small": None,
        "required": False,
        "isdefault": False,
        "default": None,
        "aliases": ["cxsca"] },
    # SAST Params
    "sast.url": {
        "type": "param",
        "help": "SAST location url",
        "description": "The URL where your SAST instance resides, such as example 'https://sast.domain.net'",
        "required": True,
        "datatype": "url" },
    "sast.username": {
        "type": "param",
        "help": "SAST username",
        "description": "The user name for the account connecting to your SAST instance",
        "required": True,
        "secret": True,
        "datatype": "string" },
    "sast.password": {
        "type": "param",
        "help": "SAST password",
        "description": "The password for the account connecting to your SAST instance",
        "required": True,
        "secret": True,
        "datatype": "string" },
    "sast.insecure": {
        "type": "flag",
        "help": "Trust any certificate",
        "description": "Use for https connections using self-signed or internal certificates",
        "required": False,
        "datatype": "bool" },
    "sast.proxy_url": {
        "type": "param",
        "help": "Proxy address",
        "description": "The proxy address, if a proxy is used",
        "required": False,
        "datatype": "url" },
    "sast.proxy_username": {
        "type": "param",
        "help": "Proxy user name",
        "description": "The user name to pass the proxy, if proxy requires authentication",
        "required": False,
        "secret": True,
        "datatype": "string" },
    "sast.proxy_password": {
        "type": "param",
        "help": "Proxy password",
        "description": "The password to pass the proxy, if proxy requires authentication",
        "required": False,
        "secret": True,
        "datatype": "string" },
    # CxONE params
    "cxone.url": {
        "type": "param",
        "help": "CxONE location url",
        "description": "The URL where your CxONE tenant resides, such as example 'https://eu.ast.checkmarx.net'",
        "required": True,
        "datatype": "url" },
    "cxone.tenant": {
        "type": "param",
        "help": "CxONE tenant name",
        "description": "The name for your CxONE tenant",
        "required": True,
        "secret": False,
        "datatype": "string" },
    "cxone.apikey": {
        "type": "param",
        "help": "CxONE apikey or client secret",
        "description": "The apikey or oidc client secret for connecting to your CxONE tenant",
        "required": True,
        "secret": True,
        "datatype": "string" },
    "cxone.iamurl": {
        "type": "param",
        "help": "CxONE iam location url",
        "description": "The URL where your CxONE IAM resides, such as example 'https://eu.iam.checkmarx.net'",
        "required": False,
        "datatype": "url" },
    "cxone.clientid": {
        "type": "param",
        "help": "CxONE oidc client id",
        "description": "The oidc client id, required for oidc, for apikey connections use ast-app or leave blank",
        "required": False,
        "datatype": "string" },
    "cxone.granttype": {
        "type": "param",
        "help": "CxONE grant type",
        "description": "The grant type, use client_credentials for oidc or refresh_token for apikey, or leave blank",
        "required": False,
        "datatype": "string" },
    "cxone.insecure": {
        "type": "flag",
        "help": "Trust any certificate",
        "description": "Use for https connections using self-signed or internal certificates",
        "required": False,
        "datatype": "bool" },
    "cxone.proxy_url": {
        "type": "param",
        "help": "Proxy address",
        "description": "The proxy address, if a proxy is used",
        "required": False,
        "datatype": "url" },
    "cxone.proxy_username": {
        "type": "param",
        "help": "Proxy user name",
        "description": "The user name to pass the proxy, if proxy requires authentication",
        "required": False,
        "secret": True,
        "datatype": "string" },
    "cxone.proxy_password": {
        "type": "param",
        "help": "Proxy password",
        "description": "The password to pass the proxy, if proxy requires authentication",
        "required": False,
        "secret": True,
        "datatype": "string" },
    # SCA Params
    "sca.url": {
        "type": "param",
        "help": "SCA api location url",
        "description": "The URL where your SCA tenant api resides, such as example 'https://api-sca.checkmarx.net'",
        "required": True,
        "datatype": "url" },
    "sca.tenant": {
        "type": "param",
        "help": "SCA tenant name",
        "description": "The name for your SCA tenant",
        "required": True,
        "secret": False,
        "datatype": "string" },
    "sca.username": {
        "type": "param",
        "help": "SCA username",
        "description": "The user name for the account connecting to your SCA tenant",
        "required": True,
        "secret": True,
        "datatype": "string" },
    "sca.password": {
        "type": "param",
        "help": "SCA password",
        "description": "The password for the account connecting to your SCA tenant",
        "required": True,
        "secret": True,
        "datatype": "string" },
    "sca.iamurl": {
        "type": "param",
        "help": "SCAE iam location url",
        "description": "The URL where your SCA access-control resides, such as example 'https://platform.checkmarx.net'",
        "required": False,
        "datatype": "url" },
    "sca.insecure": {
        "type": "flag",
        "help": "Trust any certificate",
        "description": "Use for https connections using self-signed or internal certificates",
        "required": False,
        "datatype": "bool" },
    "sca.proxy_url": {
        "type": "param",
        "help": "Proxy address",
        "description": "The proxy address, if a proxy is used",
        "required": False,
        "datatype": "url" },
    "sca.proxy_username": {
        "type": "param",
        "help": "Proxy user name",
        "description": "The user name to pass the proxy, if proxy requires authentication",
        "required": False,
        "secret": True,
        "datatype": "string" },
    "sca.proxy_password": {
        "type": "param",
        "help": "Proxy password",
        "description": "The password to pass the proxy, if proxy requires authentication",
        "required": False,
        "secret": True,
        "datatype": "string" },
    # Global
    "options": {
        "type": "group",
        "description": "Optional parameters",
        "small": None,
        "required": False,
        "isglobal": True },
    "options.no-iam": {
        "type": "flag",
        "help": "Exclude access-control/iam data",
        "description": "Exclude access-control/iam data, such as users, teams, and authentication providers",
        "required": False,
        "default": None,
        "datatype": "bool" },
    "options.detailed-users": {
        "type": "flag",
        "help": "Include users accounts and emails",
        "description": "Include all users account names and emails",
        "required": False,
        "default": None,
        "datatype": "bool" },
    "options.include-repos": {
        "type": "flag",
        "help": "Include scm repository urls",
        "description": "Include scm repository urls in projects",
        "required": False,
        "default": None,
        "datatype": "bool" },
    "options.no-scans": {
        "type": "flag",
        "help": "Exclude scan details from projects",
        "description": "Exclude last scan details from projects list",
        "required": False,
        "default": None,
        "datatype": "bool" },
    "options.no-triages": {
        "type": "flag",
        "help": "Exclude triages detection from project scans",
        "description": "Exclude triages detection from projects last scan details",
        "required": False,
        "default": None,
        "datatype": "bool" },
    "options.projects-filter": {
        "type": "flag",
        "help": "Filter the projects ids to process (default is all)",
        "description": "Filter the projects to process, using id, list of ids, or a @file with ids to include",
        "required": False,
        "default": None,
        "datatype": "id|list|file" }
}
