sast:
    url: 
    username: 
    password: 
    insecure: false
    proxy_url: 
    proxy_username: 
    proxy_password: 
cxone:
    url:
    tenant:
    apikey:
    iamurl:
    clientid:
    granttype:
    insecure: false
    proxy_url: 
    proxy_username: 
    proxy_password: 
options:
    no-iam: false
    detailed-users: false
    no-scans: false
    no-triages: false
    projects-filter: 
