#############################################################################
## The Validate job verifies pull-requests for protected branches for validation
## Executed on pull requests
#############################################################################
name: 'Validate'

on:
  pull_request:
    branches:
      - 'main'
      - 'dev'

jobs:
  ### validate source-code (lint)
  format:
    name: 'Check format (PR)'
    runs-on: ubuntu-latest
    permissions:
      contents: write 
      issues: write 
      pull-requests: write 
    steps:
      ### checkout the code (don't need submodules nor tags)
      - name: 'Checkout'
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
      ### validate source-code
      - name: 'Verify Source Code'
        uses: ./.github/actions/github-check-code
  ### perform tests
  test:
    needs: [format]
    name: 'Test (PR)'
    runs-on: ubuntu-latest
    permissions:
      contents: write 
      issues: write 
      pull-requests: write 
    steps:
      - name: 'Nothing to process'
        shell: bash
        run: |
          echo "skipped"
  ### test for security
  security:
    needs: [format,test]
    name: 'Test security (PR)'
    runs-on: ubuntu-latest
    permissions:
      contents: write 
      issues: write 
      pull-requests: write 
    steps:
      - name: 'Nothing to process'
        shell: bash
        run: |
          echo "skipped"
